name = "grain-ai"
main = "src/worker.js"
compatibility_date = "2026-09-15"
keep_vars = true

[vars]
UUID = "a51e8a7b-78b2-465a-81b9-332b26d8e9f3"
DEBUG = 1
DIRECT_FALLBACK = 0
MAX_PROXY_TRIES = 5
PROXY_TIMEOUT_MS = 6000

[secrets]
required = ["UPSTREAMS"]
