import { connect } from 'cloudflare:sockets';

const CFG = { id: 'a51e8a7b-78b2-465a-81b9-332b26d8e9f3', chunk: 64 * 1024, dnPack: 32 * 1024, dnTail: 512, dnQr: 4, upPack: 20 * 1024, maxED: 8 * 1024, proxyTries: 6, proxyTimeout: 6000 };
const dec = new TextDecoder(), enc = new TextEncoder();
const toU8 = d => d instanceof Uint8Array ? d : ArrayBuffer.isView(d) ? new Uint8Array(d.buffer, d.byteOffset, d.byteLength) : new Uint8Array(d);
const cat = (...xs) => { const out = new Uint8Array(xs.reduce((n, x) => n + x.byteLength, 0)); let o = 0; for (const x of xs) { out.set(x, o); o += x.byteLength; } return out; };
const safeClose = s => { try { s?.close?.(); } catch {} };
const debug = (env, ...a) => { if (String(env?.DEBUG || '') === '1') console.log('[GrainAI]', ...a); };

const uuidBytes = s => { const h = String(s || '').replaceAll('-', ''); if (!/^[0-9a-fA-F]{32}$/.test(h)) return null; const b = new Uint8Array(16); for (let i = 0; i < 16; i++) b[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16); return b; };
const matchID = (c, id) => c.length >= 17 && id && !id.some((v, i) => c[i + 1] !== v);
const addr = (t, b) => t === 1 ? `${b[0]}.${b[1]}.${b[2]}.${b[3]}` : t === 3 ? dec.decode(b) : `[${Array.from({ length: 8 }, (_, i) => ((b[i * 2] << 8) | b[i * 2 + 1]).toString(16)).join(':')}]`;
const parseAddr = (b, o, t) => { let l; if (t === 3) { if (o >= b.length) return { needMore: true }; l = b[o++]; } else if (t === 1) l = 4; else if (t === 4) l = 16; else return null; const n = o + l; return n > b.length ? { needMore: true } : { targetAddrBytes: b.subarray(o, n), dataOffset: n }; };
const relay = (c, id) => { if (c.length < 18) return { needMore: true }; if (!matchID(c, id)) return null; const cmdPos = 18 + c[17]; if (c.length < cmdPos + 4) return { needMore: true }; if (c[cmdPos] !== 1) return null; const o = cmdPos + 1, p = (c[o] << 8) | c[o + 1]; if (!p) return null; let t = c[o + 2]; if (t !== 1) t += 1; const a = parseAddr(c, o + 3, t); return a ? { addrType: t, ...a, port: p } : null; };

const mkK = (cap, cpy = 0) => { let q = [], h = 0, b = 0, buf = null; const e = () => h >= q.length, trim = () => { h > 32 && h * 2 >= q.length && (q = q.slice(h), h = 0); }, clear = () => { q = []; h = 0; b = 0; }; const take = () => { if (e()) return null; const d = q[h]; q[h++] = undefined; b -= d.byteLength; trim(); return d; }; const sow = d => { const n = d?.byteLength || 0; return !n || (q.push(d), b += n, 1); }; const pack = d => { d ||= take(); if (!d || e()) return [d, 0]; let n = d.byteLength, j = h; while (j < q.length) { const x = q[j], nn = n + x.byteLength; if (nn > cap) break; n = nn; j++; } if (j === h) return [d, 0]; const out = buf ||= new Uint8Array(cap); out.set(d); for (let o = d.byteLength; h < j;) { const x = q[h]; q[h++] = undefined; b -= x.byteLength; out.set(x, o); o += x.byteLength; } trim(); const u = out.subarray(0, n); return [cpy ? u.slice() : u, 1]; }; return { e, get b() { return b; }, clear, take, sow, pack }; };
const mkQ = cap => { const k = mkK(cap); return { get empty() { return k.e(); }, clear: k.clear, sow: k.sow, bundle: d => k.pack(d) }; };
const mkDn = w => { const cap = CFG.dnPack, tail = CFG.dnTail, low = Math.max(4096, tail * 12), k = mkK(cap, 1); let tp = 0, gen = 0, qk = 0, qr = 0; const reap = () => { tp && clearTimeout(tp); tp = 0; qr = 0; for (;;) { const [u] = k.pack(); if (!u) break; w.send(u); } }; const ripen = () => { if (k.e() || tp) return; if (k.b >= cap || cap - k.b < tail) return reap(); tp = setTimeout(() => { tp = 0; if (k.e()) return; if (k.b >= cap || cap - k.b < tail) return reap(); if (qr < CFG.dnQr && (gen !== qk || k.b < low)) { qr++; qk = gen; return ripen(); } reap(); }, 1); }; return { send(u) { let o = 0, n = u?.byteLength || 0; if (!n) return; while (o < n) { const m = Math.min(cap - k.b, n - o); if (!m) { reap(); continue; } k.sow(o || m !== n ? u.subarray(o, o + m) : u); gen++; o += m; if (k.b >= cap || cap - k.b < tail) reap(); else ripen(); } }, reap }; };
const mill = async (rd, w) => { let r, byob = false; const tx = mkDn(w); try { try { r = rd.getReader({ mode: 'byob' }); byob = true; } catch { r = rd.getReader(); } if (byob) { let buf = new ArrayBuffer(CFG.chunk); for (;;) { const { done, value: v } = await r.read(new Uint8Array(buf, 0, CFG.chunk)); if (done) break; if (!v?.byteLength) continue; if (v.byteLength >= (CFG.chunk >> 1)) tx.reap(), w.send(v), buf = new ArrayBuffer(CFG.chunk); else tx.send(v.slice()), buf = v.buffer.byteLength >= CFG.chunk ? v.buffer : new ArrayBuffer(CFG.chunk); } } else { for (;;) { const { done, value } = await r.read(); if (done) break; if (!value?.byteLength) continue; const v = toU8(value); if (v.byteLength >= (CFG.chunk >> 1)) tx.reap(), w.send(v); else tx.send(v.slice()); } } tx.reap(); } catch {} finally { try { tx.reap(); } catch {} try { r?.releaseLock(); } catch {} } };

const decode = s => { try { return decodeURIComponent(s || ''); } catch { return s || ''; } };
const parseProxyURL = raw => { try { const u = new URL(raw); const scheme = u.protocol.slice(0, -1).toLowerCase(); if (!['socks5', 'http', 'https'].includes(scheme)) return null; const port = +(u.port || (scheme === 'https' ? 443 : scheme === 'http' ? 8080 : 1080)); return u.hostname && port ? { scheme, host: u.hostname, port, user: decode(u.username), pass: decode(u.password) } : null; } catch { return null; } };
const parseResultLine = line => { const p = line.split('|').map(x => x.trim()); if (!p[0]) return null; const m = p[0].match(/^(\[[^\]]+\]|[^:]+):(\d+)(?::(socks5|https?|http))?$/i); if (!m) return null; const host = m[1].replace(/^\[|\]$/g, ''), port = +m[2], tag = (m[3] || '').toLowerCase(); const cred = p[1] || '', ci = cred.indexOf(':'); const user = ci >= 0 ? cred.slice(0, ci) : '', pass = ci >= 0 ? cred.slice(ci + 1) : ''; const scheme = tag === 'socks5' || (!tag && (user || pass)) ? 'socks5' : 'http'; return { scheme, host, port, user, pass }; };
const parseUpstreams = text => { const out = [], seen = new Set(); for (const rawLine of String(text || '').split(/\r?\n/)) { const line = rawLine.trim(); if (!line || line.startsWith('#')) continue; const parts = line.includes('|') ? [line] : line.split(/[;,\s]+/).filter(Boolean); for (const x of parts) { const p = x.includes('://') ? parseProxyURL(x) : x.includes('|') ? parseResultLine(x) : parseProxyURL(`socks5://${x}`); if (!p || !p.host || !p.port) continue; const k = `${p.scheme}|${p.host}|${p.port}|${p.user}|${p.pass}`; if (!seen.has(k)) seen.add(k), out.push(p); } } return out; };
const shuffle = a => { a = a.slice(); for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; };
const label = p => `${p.scheme}://${p.host}:${p.port}`;

const wrapReadable = (prefix, source, heldReader) => { if (!prefix?.byteLength) { try { heldReader.releaseLock(); } catch {} return source; } let first = prefix; return new ReadableStream({ type: 'bytes', pull: async c => { if (first) { const x = first; first = null; c.enqueue(x); return; } const { done, value } = await heldReader.read(); if (done) { try { heldReader.releaseLock(); } catch {} c.close(); return; } if (value?.byteLength) c.enqueue(toU8(value)); }, cancel: async reason => { try { await heldReader.cancel(reason); } catch {} try { heldReader.releaseLock(); } catch {} } }); };
const proxiedSocket = (socket, readable) => ({ readable, writable: socket.writable, opened: socket.opened, closed: socket.closed, close: () => socket.close() });
const b64 = s => { const u = enc.encode(s); let x = ''; for (let i = 0; i < u.length; i++) x += String.fromCharCode(u[i]); return btoa(x); };

const bufferedReader = reader => { let buf = new Uint8Array(0); const fill = async n => { while (buf.byteLength < n) { const { done, value } = await reader.read(); if (done) throw new Error('proxy EOF'); const v = toU8(value); buf = buf.byteLength ? cat(buf, v) : v.slice(); } }; return { async take(n) { await fill(n); const out = buf.slice(0, n); buf = buf.slice(n); return out; }, async until(marker, max = 16384) { for (;;) { for (let i = 0; i <= buf.length - marker.length; i++) { let ok = true; for (let j = 0; j < marker.length; j++) if (buf[i + j] !== marker[j]) { ok = false; break; } if (ok) { const e = i + marker.length, out = buf.slice(0, e); buf = buf.slice(e); return out; } } if (buf.byteLength >= max) throw new Error('proxy header too large'); const { done, value } = await reader.read(); if (done) throw new Error('proxy EOF'); const v = toU8(value); buf = buf.byteLength ? cat(buf, v) : v.slice(); } }, rest() { return buf; } }; };

const openSocket = async (proxy, timeoutMs) => { let socket = null, timer = null; try { socket = connect({ hostname: proxy.host, port: proxy.port }, { secureTransport: proxy.scheme === 'https' ? 'on' : 'off', allowHalfOpen: true }); await Promise.race([socket.opened, new Promise((_, reject) => { timer = setTimeout(() => { safeClose(socket); reject(new Error('proxy connect timeout')); }, timeoutMs); })]); return socket; } finally { timer && clearTimeout(timer); } };

const socksRequestAddr = target => { if (target.addrType === 1) return cat(new Uint8Array([1]), target.addrBytes); if (target.addrType === 4) return cat(new Uint8Array([4]), target.addrBytes); const d = target.addrBytes; if (!d?.byteLength || d.byteLength > 255) throw new Error('bad target domain'); return cat(new Uint8Array([3, d.byteLength]), d); };
const dialSocks5 = async (proxy, target, timeoutMs) => { let s = null, r = null, w = null, timer = null; try { s = await openSocket(proxy, timeoutMs); timer = setTimeout(() => safeClose(s), timeoutMs); r = s.readable.getReader(); w = s.writable.getWriter(); const br = bufferedReader(r), auth = !!(proxy.user || proxy.pass); await w.write(auth ? new Uint8Array([5, 2, 0, 2]) : new Uint8Array([5, 1, 0])); let x = await br.take(2); if (x[0] !== 5 || x[1] === 255) throw new Error('SOCKS auth method rejected'); if (x[1] === 2) { const u = enc.encode(proxy.user), p = enc.encode(proxy.pass); if (u.length > 255 || p.length > 255) throw new Error('SOCKS credentials too long'); await w.write(cat(new Uint8Array([1, u.length]), u, new Uint8Array([p.length]), p)); x = await br.take(2); if (x[1] !== 0) throw new Error('SOCKS authentication failed'); } else if (x[1] !== 0) throw new Error(`unsupported SOCKS method ${x[1]}`); const a = socksRequestAddr(target), pp = new Uint8Array([target.port >> 8, target.port & 255]); await w.write(cat(new Uint8Array([5, 1, 0]), a, pp)); const h = await br.take(4); if (h[0] !== 5 || h[1] !== 0) throw new Error(`SOCKS CONNECT failed ${h[1]}`); if (h[3] === 1) await br.take(6); else if (h[3] === 4) await br.take(18); else if (h[3] === 3) { const n = (await br.take(1))[0]; await br.take(n + 2); } else throw new Error('bad SOCKS reply'); const rest = br.rest(); try { w.releaseLock(); } catch {} w = null; const readable = wrapReadable(rest, s.readable, r); r = null; return proxiedSocket(s, readable); } catch (e) { try { w?.releaseLock(); } catch {} try { r?.releaseLock(); } catch {} safeClose(s); throw e; } finally { timer && clearTimeout(timer); } };

const dialHttp = async (proxy, target, timeoutMs) => { let s = null, r = null, w = null, timer = null; try { s = await openSocket(proxy, timeoutMs); timer = setTimeout(() => safeClose(s), timeoutMs); r = s.readable.getReader(); w = s.writable.getWriter(); const br = bufferedReader(r), authority = target.addrType === 4 ? `[${target.host.replace(/^\[|\]$/g, '')}]:${target.port}` : `${target.host}:${target.port}`, auth = proxy.user || proxy.pass ? `Proxy-Authorization: Basic ${b64(`${proxy.user}:${proxy.pass}`)}\r\n` : ''; const req = `CONNECT ${authority} HTTP/1.1\r\nHost: ${authority}\r\n${auth}Proxy-Connection: Keep-Alive\r\nConnection: Keep-Alive\r\n\r\n`; await w.write(enc.encode(req)); const head = await br.until(new Uint8Array([13, 10, 13, 10])); const first = dec.decode(head).split('\r\n', 1)[0], m = first.match(/^HTTP\/\d(?:\.\d)?\s+(\d{3})\b/i); if (!m || +m[1] < 200 || +m[1] >= 300) throw new Error(`HTTP CONNECT rejected: ${first || 'invalid response'}`); const rest = br.rest(); try { w.releaseLock(); } catch {} w = null; const readable = wrapReadable(rest, s.readable, r); r = null; return proxiedSocket(s, readable); } catch (e) { try { w?.releaseLock(); } catch {} try { r?.releaseLock(); } catch {} safeClose(s); throw e; } finally { timer && clearTimeout(timer); } };

const dialOneProxy = (proxy, target, timeoutMs) => proxy.scheme === 'socks5' ? dialSocks5(proxy, target, timeoutMs) : dialHttp(proxy, target, timeoutMs);
const directDial = async (req, target) => { const f = req?.fetcher; if (f?.connect) { const s = f.connect({ hostname: target.host, port: target.port }); await s.opened; return s; } const s = connect({ hostname: target.host, port: target.port }, { allowHalfOpen: true }); await s.opened; return s; };
const dialTarget = async (req, env, target) => { const list = parseUpstreams(env?.UPSTREAMS), timeoutMs = Math.max(1000, Number(env?.PROXY_TIMEOUT_MS) || CFG.proxyTimeout), maxTries = Math.max(1, Math.min(list.length || 1, Number(env?.MAX_PROXY_TRIES) || CFG.proxyTries)); if (list.length) { const candidates = shuffle(list).slice(0, maxTries); let last; for (const p of candidates) { try { debug(env, 'try', label(p), '->', `${target.host}:${target.port}`); const s = await dialOneProxy(p, target, timeoutMs); debug(env, 'connected', label(p)); return s; } catch (e) { last = e; debug(env, 'failed', label(p), e?.message || e); } } if (String(env?.DIRECT_FALLBACK || '') !== '1') throw last || new Error('all upstreams failed'); } return directDial(req, target); };

const decodeEarly = s => { if (!s || s.length > Math.ceil(CFG.maxED * 4 / 3) + 4) return null; try { const u = /** @type {*} */ (Uint8Array).fromBase64(s, { alphabet: 'base64url' }); return u.byteLength <= CFG.maxED ? u : null; } catch { return null; } };

const ws = async (req, env) => { const id = uuidBytes(env?.UUID || CFG.id); if (!id) return new Response('Bad UUID', { status: 500 }); const [client, server] = Object.values(new WebSocketPair()); try { server.accept({ allowHalfOpen: true }); } catch { server.accept(); } server.binaryType = 'arraybuffer'; const ed = decodeEarly(req.headers.get('sec-websocket-protocol')); let curW = null, sock = null, closed = false, busy = false, init = null; const uq = mkQ(CFG.upPack); const wither = () => { if (closed) return; closed = true; uq.clear(); try { curW?.releaseLock(); } catch {} safeClose(sock); try { server.close(); } catch {} }; const sow = d => { const u = toU8(d); if (!u.byteLength) return 1; return uq.sow(u); }; const thresh = async () => { if (busy || closed) return; busy = true; try { for (;;) { if (closed) break; if (!sock) { const [piece] = uq.bundle(); if (!piece) break; const d = init ? cat(init, piece) : piece, r = relay(d, id); if (r?.needMore) { if (d.byteLength > 2048) throw new Error('VLESS header too large'); init = d.slice(); continue; } init = null; if (!r) throw new Error('invalid or non-TCP VLESS request'); server.send(new Uint8Array([d[0], 0])); const host = addr(r.addrType, r.targetAddrBytes), target = { host, port: r.port, addrType: r.addrType, addrBytes: r.targetAddrBytes }; const payload = d.subarray(r.dataOffset); sock = await dialTarget(req, env, target); curW = sock.writable.getWriter(); const [first] = uq.bundle(payload); if (first?.byteLength) await curW.write(first); mill(sock.readable, server).finally(wither); continue; } const [d] = uq.bundle(); if (!d) break; await curW.write(d); } } catch (e) { debug(env, 'tunnel closed', e?.message || e); wither(); } finally { busy = false; !uq.empty && !closed && thresh(); } }; if (ed && sow(ed)) thresh(); server.addEventListener('message', e => { if (!closed && sow(e.data)) thresh(); }); server.addEventListener('close', wither); server.addEventListener('error', wither); return new Response(null, { status: 101, webSocket: client, headers: { 'Sec-WebSocket-Extensions': '' } }); };

export default { fetch: (req, env) => req.headers.get('Upgrade')?.toLowerCase() === 'websocket' ? ws(req, env) : new Response('GrainAI') };
